version: "{build}"

platform:
  - x64

install:
  - appveyor DownloadFile http://curl.haxx.se/ca/cacert.pem -FileName C:\cacert.pem

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%\consul
  - download.bat
  - cpack consul.nuspec

test_script:
  - cinst consul -source %APPVEYOR_BUILD_FOLDER%\consul
  - cuninst consul

artifacts:
  - path: '**\*.nupkg'

deploy: off
